services:
  migrate-auth:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    container_name: third-auth-migrate
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    command: ["/app/auth-migrate"]
    environment:
      APP_ENV: development
      HTTP_PORT: 8080

      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: app
      DB_SSL_MODE: disable

      JWT_SECRET: super-secret-dev-key
      JWT_ISSUER: auth-service
      JWT_ACCESS_TOKEN_TTL_MINUTES: 60
    networks:
      - third-shop-micro-net

  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      minio-init:
        condition: service_completed_successfully
    environment:
      APP_ENV: development
      HTTP_PORT: 8080

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: app
      DB_SSL_MODE: disable

      JWT_SECRET: super-secret-dev-key
      JWT_ISSUER: auth-service
      JWT_ACCESS_TOKEN_TTL_MINUTES: 60
    ports:
      - "8080:8080"

volumes:
  auth_postgres_data:
